### ISSUE TITLE
Swapchain isn't recreating properly

### ISSUE THREAD

**Issue by cullvox** [cullvox/bluemetal#1]
When the vulkan swapchain is recreated when selecting another present mode the program crashes. More debugging is required since validation layers have been disabled but it will be much easier if they are re enabled. This issue is not persistent across all platforms.

**Comment by cadenmiller** [comment]
Figured out that the issue is in when the swapchain is recreated. Currently the setup recreates the swapchain within the render loop. That can't happen since we are currently using the swapchain, maybe there is a way that the frame could be cancelled?

**Comment by cadenmiller** [comment]
Can now confirm that this issue is on all platforms. Validation layers were having issues being enabled on NixOS using VS Code.
